<?php
$_lang['pageshrink'] = 'PageShrink';
$_lang['pageshrink.desc'] = 'PageShrink is a MODX Revolution plugin that minifies HTML, CSS, and JavaScript output.';

$_lang['setting_pageshrink.resource_shrink'] = 'Shrink Resources';
$_lang['setting_pageshrink.resource_shrink_desc'] = 'Minify the output of Resources.';
$_lang['setting_pageshrink.cache_resource_shrink'] = 'Cache Resource Shrink';
$_lang['setting_pageshrink.cache_resource_shrink_desc'] = 'Cache the minified output of Resources.';

$_lang['setting_pageshrink.optimize_via_html_dom_parser'] = 'doOptimizeViaHtmlDomParser';
$_lang['setting_pageshrink.optimize_via_html_dom_parser_desc'] = 'optimize html via "HtmlDomParser()"';
$_lang['setting_pageshrink.remove_comments'] = 'doRemoveComments';
$_lang['setting_pageshrink.remove_comments_desc'] = 'remove default HTML comments (depends on "doOptimizeViaHtmlDomParser(true)")';
$_lang['setting_pageshrink.sum_up_whitespace'] = 'doSumUpWhitespace';
$_lang['setting_pageshrink.sum_up_whitespace_desc'] = 'sum-up extra whitespace from the Dom (depends on "doOptimizeViaHtmlDomParser(true)")';
$_lang['setting_pageshrink.remove_whitespace_around_tags'] = 'doRemoveWhitespaceAroundTags';
$_lang['setting_pageshrink.remove_whitespace_around_tags_desc'] = 'remove whitespace around tags (depends on "doOptimizeViaHtmlDomParser(true)")';
$_lang['setting_pageshrink.optimize_attributes'] = 'doOptimizeAttributes';
$_lang['setting_pageshrink.optimize_attributes_desc'] = 'optimize html attributes (depends on "doOptimizeViaHtmlDomParser(true)")';
$_lang['setting_pageshrink.remove_http_prefix_from_attributes'] = 'doRemoveHttpPrefixFromAttributes';
$_lang['setting_pageshrink.remove_http_prefix_from_attributes_desc'] = 'remove optional "http:"-prefix from attributes (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.keep_http_prefix_on_external_attributes'] = 'doKeepHttpAndHttpsPrefixOnExternalAttributes';
$_lang['setting_pageshrink.keep_http_prefix_on_external_attributes_desc'] = 'keep "http:"- and "https:"-prefix for all external links';
$_lang['setting_pageshrink.remove_default_attributes'] = 'doRemoveDefaultAttributes';
$_lang['setting_pageshrink.remove_default_attributes_desc'] = 'remove defaults (depends on "doOptimizeAttributes(true)" | disabled by default)';
$_lang['setting_pageshrink.remove_anchor_name'] = 'doRemoveDeprecatedAnchorName';
$_lang['setting_pageshrink.remove_anchor_name_desc'] = 'remove deprecated anchor-jump (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.remove_script_charset_attribute'] = 'doRemoveDeprecatedScriptCharsetAttribute';
$_lang['setting_pageshrink.remove_script_charset_attribute_desc'] = 'remove deprecated charset-attribute - the browser will use the charset from the HTTP-Header, anyway (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.remove_type_from_script_tag'] = 'doRemoveDeprecatedTypeFromScriptTag';
$_lang['setting_pageshrink.remove_type_from_script_tag_desc'] = 'remove deprecated script-mime-types (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.remove_type_from_style_link_tag'] = 'doRemoveDeprecatedTypeFromStyleAndLinkTag';
$_lang['setting_pageshrink.remove_type_from_style_link_tag_desc'] = 'remove "type=text/css" from all links and styles';
$_lang['setting_pageshrink.remove_default_media_typed_link_tag'] = 'doRemoveDefaultMediaTypeFromStyleAndLinkTag';
$_lang['setting_pageshrink.remove_default_media_typed_link_tag_desc'] = 'remove "media="all" from all links and style';
$_lang['setting_pageshrink.remove_default_type_from_button'] = 'doRemoveDefaultTypeFromButton';
$_lang['setting_pageshrink.remove_default_type_from_button_desc'] = 'remove type="submit" from button tags';
$_lang['setting_pageshrink.remove_empty_attributes'] = 'doRemoveEmptyAttributes';
$_lang['setting_pageshrink.remove_empty_attributes_desc'] = 'remove some empty attributes (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.remove_value_from_empty_input'] = 'doRemoveValueFromEmptyInput';
$_lang['setting_pageshrink.remove_value_from_empty_input_desc'] = 'remove value=\'\' from empty input (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.sort_css_class_names'] = 'doSortCssClassNames';
$_lang['setting_pageshrink.sort_css_class_names_desc'] = 'sort css-class-names, for better gzip results (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.sort_html_attributes'] = 'doSortHtmlAttributes';
$_lang['setting_pageshrink.sort_html_attributes_desc'] = 'sort html-attributes, for better gzip results (depends on "doOptimizeAttributes(true)")';
$_lang['setting_pageshrink.remove_spaces_between_tags'] = 'doRemoveSpacesBetweenTags';
$_lang['setting_pageshrink.remove_spaces_between_tags_desc'] = 'remove more (aggressive) spaces in the dom (disabled by default)';
$_lang['setting_pageshrink.remove_omitted_quotes'] = 'doRemoveOmittedQuotes';
$_lang['setting_pageshrink.remove_omitted_quotes_desc'] = 'remove quotes e.g. class="lall" => class=lall';
$_lang['setting_pageshrink.remove_omitted_html_tags'] = 'doRemoveOmittedHtmlTags';
$_lang['setting_pageshrink.remove_omitted_html_tags_desc'] = 'remove ommitted html end tags';
$_lang['setting_pageshrink.remove_type_from_stylesheet_link'] = 'doRemoveDeprecatedTypeFromStylesheetLink';
$_lang['setting_pageshrink.remove_type_from_stylesheet_link_desc'] = 'remove "type=text/css" for css links (depends on "doOptimizeAttributes(true)")';
$_lang['area_pageshrink.minify_options'] = 'Minify Options';
